  panelopts                            = True
  panelopts@amJust                     = "TopLeft"
  panelopts@gsnOrientation             = "landscape"
  panelopts@gsnPanelLabelBar           = False
  panelopts@gsnPanelRowSpec            = True
  panelopts@gsnMaximize                = True                          ; maximize plot in frame
  panelopts@gsnBoxMargin               = 0
  panelopts@gsnPanelYWhiteSpacePercent = 0
  panelopts@gsnPanelXWhiteSpacePercent = 5
  panelopts@amJust                     = "TopLeft"

